#!/bin/bash
# Demo: Complete Structured PubMed Workflow
# Shows how to use the university folder structure system

echo "🎯 PubMed Structured Workflow Demo"
echo "=================================="
echo "This demo shows how to search, parse, and organize PubMed data"
echo "using your university folder structure."
echo ""

# Step 1: Generate scripts
echo "📜 Step 1: Generate Structured Scripts"
echo "--------------------------------------"
echo "python3 generate_edirect_scripts_structured.py"
echo ""
echo "This creates scripts that save .txt files to:"
echo "data/publications/pubmed/CA/ON/CA-ON-002_mcmaster.ca/"
echo ""

# Step 2: Run a test search
echo "📋 Step 2: Available Search Options"
echo "-----------------------------------"
echo "Individual searches:"
echo "  ./edirect_scripts_structured/search_Gordon_Guyatt.sh"
echo "  ./edirect_scripts_structured/search_Salim_Yusuf.sh"
echo ""
echo "Batch search all faculty:"
echo "  ./edirect_scripts_structured/search_all_faculty_structured.sh"
echo ""
echo "Custom search:"
echo "  ./edirect_scripts_structured/custom_search_structured.sh \"Faculty Name\" \"CA-ON-002_mcmaster.ca\""
echo ""

# Step 3: Parse results
echo "🔍 Step 3: Parse Results"
echo "------------------------"
echo "After searches complete, parse all university data:"
echo "python3 parse_medline_structured.py data/publications/pubmed/"
echo ""
echo "This creates:"
echo "  • Individual faculty JSON files"
echo "  • Combined publications JSON/CSV"
echo "  • University summary with statistics"
echo "  • Parse summary with details"
echo ""

# Step 4: Transfer and import
echo "📤 Step 4: Transfer to VPS and Import"
echo "-------------------------------------"
echo "Transfer parsed data to VPS:"
echo "scp -r parsed_publications_structured/ xeradb@your-vps:/var/www/ff/"
echo ""
echo "Import to PostgreSQL database (on VPS):"
echo "python3 import_pubmed_data.py parsed_publications_structured/"
echo ""

# Step 5: Expected results
echo "📊 Step 5: Expected Results"
echo "---------------------------"
echo "Folder structure after completion:"
echo "data/publications/pubmed/"
echo "├── CA/"
echo "│   └── ON/"
echo "│       └── CA-ON-002_mcmaster.ca/"
echo "│           ├── Gordon_Guyatt_publications.txt"
echo "│           ├── Salim_Yusuf_publications.txt"
echo "│           ├── Hertzel_Gerstein_publications.txt"
echo "│           ├── Mohit_Bhandari_publications.txt"
echo "│           ├── Mark_Crowther_publications.txt"
echo "│           ├── Deborah_Cook_publications.txt"
echo "│           ├── Andrew_Mente_publications.txt"
echo "│           ├── Bram_Rochwerg_publications.txt"
echo "│           ├── Holger_Schunemann_publications.txt"
echo "│           └── Jan_Brozek_publications.txt"
echo ""

echo "Database results:"
echo "  • Publications linked to professors"
echo "  • University information preserved" 
echo "  • Faculty profiles with publication counts"
echo "  • Homepage displays publication metrics"
echo ""

# Benefits
echo "🎯 Benefits of Structured Approach"
echo "----------------------------------"
echo "✅ Organized by university (scalable)"
echo "✅ Easy to find specific faculty files"
echo "✅ University context preserved" 
echo "✅ Compatible with existing structure"
echo "✅ Ready for multi-university expansion"
echo "✅ Clear separation of data sources"
echo ""

# Quick start
echo "🚀 Quick Start"
echo "--------------"
echo "To begin right now:"
echo ""
echo "1. Test single faculty:"
echo "   ./edirect_scripts_structured/search_Gordon_Guyatt.sh"
echo ""
echo "2. Or run all faculty:"
echo "   ./edirect_scripts_structured/search_all_faculty_structured.sh"
echo ""
echo "3. Parse when complete:"
echo "   python3 parse_medline_structured.py data/publications/pubmed/"
echo ""
echo "4. Import to VPS:"
echo "   python3 import_pubmed_data.py parsed_publications_structured/"
echo ""

echo "🎉 Your FacultyFinder will have properly organized publication data!" 